// AUTO-GENERATED by @pro-laico/core/scripts/appendPayloadAugment.mjs — do not edit by hand.
// Regenerated whenever `pnpm generate:types` runs.

import type * as G from './payload-types'

declare module '@pro-laico/core' {
  interface PayloadAugment {
    DesignSet: G.DesignSet
  }
}
