/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicChildVariants".
 */
export type AtomicChildVariants = 'tag' | 'form' | 'input' | 'button';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicTagType".
 */
export type AtomicTagType =
  | (
      | 'div'
      | 'section'
      | 'fragment'
      | 'article'
      | 'nav'
      | 'label'
      | 'ul'
      | 'ol'
      | 'li'
      | 'span'
      | 'h1'
      | 'h2'
      | 'h3'
      | 'h4'
      | 'h5'
      | 'h6'
      | 'code'
    )
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicButtonTypes".
 */
export type AtomicButtonTypes = ('link' | 'regular' | 'portal') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicInputTypes".
 */
export type AtomicInputTypes = ('text' | 'textarea' | 'email' | 'number' | 'checkbox' | 'radio') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicButtonPortalTypes".
 */
export type AtomicButtonPortalTypes = ('popover' | 'dialog') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicButtonLinkTypes".
 */
export type AtomicButtonLinkTypes = ('internalLink' | 'externalLink' | 'download' | 'email' | 'phone') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChildBlocks".
 */
export type ChildBlocks = (
  | AtomicChild
  | SimpleTextChild
  | RichTextChild
  | ImageChild
  | VideoChild
  | IconChild
  | SVGChild
)[];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleTextTagType".
 */
export type SimpleTextTagType =
  | 'p'
  | 'span'
  | 'fragment'
  | 'div'
  | 'label'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'code';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActionBlocks".
 */
export type ActionBlocks = (
  | ActSetCC
  | ActCCToDA
  | ActSetTheme
  | ActResetForm
  | ActDSSetBool
  | ActSubmitForm
  | ActDSBoolToDA
  | ActDSTextToDA
  | ActDSCycleText
  | ActFormErrorToDA
  | ActSetPortalOpen
  | ActFormStatusToDA
)[];
/**
 * Type: {@link CookieConsentPerform}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CookieConsentPerform".
 */
export type CookieConsentPerform = 'preference' | 'accept' | 'decline';
/**
 * Type: {@link CookieConsentPreferenceKeys}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CookieConsentPreferenceKeys".
 */
export type CookieConsentPreferenceKeys =
  | 'functional'
  | 'security'
  | 'analytics'
  | 'marketing'
  | 'userData'
  | 'adPersonalization'
  | 'contentPersonalization';
/**
 * Type: {@link CookieConsentListen}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CookieConsentListen".
 */
export type CookieConsentListen = 'preference' | 'accept' | 'decline' | 'hasConsented' | 'previouslyConsented';
/**
 * Type: {@link ThemePerform}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThemePerform".
 */
export type ThemePerform = 'light' | 'dark' | 'system' | 'cycle';
/**
 * Type: {@link ActionBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActionBlockType".
 */
export type ActionBlockType =
  | 'ActSetCC'
  | 'ActCCToDA'
  | 'ActSetTheme'
  | 'ActResetForm'
  | 'ActDSSetBool'
  | 'ActSubmitForm'
  | 'ActDSBoolToDA'
  | 'ActDSTextToDA'
  | 'ActDSCycleText'
  | 'ActFormErrorToDA'
  | 'ActSetPortalOpen'
  | 'ActFormStatusToDA';
/**
 * Type: {@link Runner}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Runner".
 */
export type Runner = RunSetCC | RunSetTheme | RunCycleText | RunSetBool | RunResetForm | RunSubmitForm;
/**
 * Type: {@link Runners}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Runners".
 */
export type Runners = Runner[];
/**
 * Type: {@link Attributer}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Attributer".
 */
export type Attributer = AttCCToDA | AttBoolToDA | AttTextToDA | AttFormErrorToDA | AttFormStatusToDA;
/**
 * Type: {@link Attributers}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Attributers".
 */
export type Attributers = Attributer[];
/**
 * Add static data attributes to the element.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaticDataAttributes".
 */
export type StaticDataAttributes =
  | {
      /**
       * The name of the key to set.
       */
      key: string;
      /**
       * The string value of the data-key. Set to "true" to have a data attribute applied with no string value.
       */
      value: string;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoTagType".
 */
export type VideoTagType = 'div' | 'section';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormSanitationBlocks".
 */
export type FormSanitationBlocks = FsCombineTwoFields[];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormValidationBlocks".
 */
export type FormValidationBlocks = FvIsUnique[];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormRateLimitBlocks".
 */
export type FormRateLimitBlocks = FrlSimpleSlidingWindow[];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InputSanitationBlocks".
 */
export type InputSanitationBlocks = IsTrimText[];
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InputValidationBlocks".
 */
export type InputValidationBlocks = (IvContains | IvDoesNotContain)[];
/**
 * Determines what suggestions are shown by the browser for the input.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AutocompleteOptions".
 */
export type AutocompleteOptions =
  | (
      | 'on'
      | 'off'
      | 'name'
      | 'given-name'
      | 'additional-name'
      | 'family-name'
      | 'nickname'
      | 'username'
      | 'new-password'
      | 'current-password'
      | 'one-time-code'
      | 'email'
      | 'tel'
      | 'tel-country-code'
      | 'tel-national'
      | 'tel-area-code'
      | 'tel-local'
      | 'tel-extension'
      | 'impp'
      | 'street-address'
      | 'address-line1'
      | 'address-line2'
      | 'address-line3'
      | 'address-level1'
      | 'address-level2'
      | 'address-level3'
      | 'address-level4'
      | 'country'
      | 'country-name'
      | 'postal-code'
      | 'organization'
      | 'organization-title'
      | 'url'
      | 'photo'
      | 'bday'
      | 'bday-day'
      | 'bday-month'
      | 'bday-year'
      | 'sex'
    )
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BackdropChildren".
 */
export type BackdropChildren = SVGChild[];
/**
 * Determines if you can interact outside the opened portal. Defaults to window, which allows interaction outside the portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trapFocus".
 */
export type TrapFocus = ('trap-focus' | 'Block' | 'Window') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GenericFontFamily".
 */
export type GenericFontFamily = 'sans' | 'serif' | 'mono' | 'display';
/**
 * Type: {@link TokenString}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TokenString".
 */
export type TokenString =
  | {
      name: string;
      value: string;
    }[]
  | null;
/**
 * Type: {@link DesignSetColors}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DesignSetColors".
 */
export type DesignSetColors = {
  name: string;
  light: string;
  dark: string;
}[];
/**
 * Type: {@link TokenStringArray}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TokenStringArray".
 */
export type TokenStringArray =
  | {
      name: string;
      values: {
        value: string;
      }[];
    }[]
  | null;
/**
 * Type: {@link SOSA} String | String[]
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SOSA".
 */
export type SOSA = string | string[];
/**
 * Select the tag the nested styles will apply to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TypographySupportedTags".
 */
export type TypographySupportedTags =
  | (
      | 'headings'
      | 'h1'
      | 'h2'
      | 'h3'
      | 'h4'
      | 'h5'
      | 'h6'
      | 'th'
      | 'p'
      | 'a'
      | 'blockquote'
      | 'figure'
      | 'figcaption'
      | 'strong'
      | 'em'
      | 'kbd'
      | 'code'
      | 'pre'
      | 'ol'
      | 'ul'
      | 'li'
      | 'table'
      | 'thead'
      | 'tr'
      | 'td'
      | 'img'
      | 'video'
      | 'hr'
    )
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * Type: {@link CollectionThatUsesAtomicHookSlug}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionThatUsesAtomicHookSlug".
 */
export type CollectionThatUsesAtomicHookSlug = 'pages' | 'footer' | 'header' | 'iconSet' | 'designSet' | 'shortcutSet';
/**
 * Type: {@link CollectionWithStoredAtomicClassesSlug}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionWithStoredAtomicClassesSlug".
 */
export type CollectionWithStoredAtomicClassesSlug = 'pages' | 'footer' | 'header';
/**
 * Type: {@link CollectionThatUsesCSSProcessorSlug}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionThatUsesCSSProcessorSlug".
 */
export type CollectionThatUsesCSSProcessorSlug = 'designSet' | 'shortcutSet' | 'pages' | 'footer' | 'header';
/**
 * Type: {@link CollectionWithStoredAtomicFormsSlug}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionWithStoredAtomicFormsSlug".
 */
export type CollectionWithStoredAtomicFormsSlug = 'pages' | 'footer' | 'header';
/**
 * Type: {@link CollectionWithStoredAtomicActionsSlug}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionWithStoredAtomicActionsSlug".
 */
export type CollectionWithStoredAtomicActionsSlug = 'pages' | 'footer' | 'header';
/**
 * Type: {@link ThemeKeys}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThemeKeys".
 */
export type ThemeKeys = 'mode';
/**
 * Type: {@link ThemeListen}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThemeListen".
 */
export type ThemeListen = 'mode';
/**
 * Type: {@link RunnerType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunnerType".
 */
export type RunnerType = 'RunSetCC' | 'RunSetTheme' | 'RunCycleText' | 'RunSetBool' | 'RunResetForm' | 'RunSubmitForm';
/**
 * Type: {@link AttributerType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttributerType".
 */
export type AttributerType = 'AttCCToDA' | 'AttBoolToDA' | 'AttTextToDA' | 'AttFormErrorToDA' | 'AttFormStatusToDA';
/**
 * Type: {@link InputSanitationBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InputSanitationBlockType".
 */
export type InputSanitationBlockType = 'IsTrimText';
/**
 * Type: {@link InputValidationBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InputValidationBlockType".
 */
export type InputValidationBlockType = 'IvContains' | 'IvDoesNotContain';
/**
 * Type: {@link FormRateLimitBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormRateLimitBlockType".
 */
export type FormRateLimitBlockType = 'FrlSimpleSlidingWindow';
/**
 * Type: {@link FormSanitationBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormSanitationBlockType".
 */
export type FormSanitationBlockType = 'FsCombineTwoFields';
/**
 * Type: {@link FormValidationBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormValidationBlockType".
 */
export type FormValidationBlockType = 'FvIsUnique';
/**
 * Type: {@link ChildBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChildBlockType".
 */
export type ChildBlockType =
  | 'AtomicChild'
  | 'SimpleTextChild'
  | 'RichTextChild'
  | 'ImageChild'
  | 'VideoChild'
  | 'IconChild'
  | 'SVGChild';
/**
 * Type: {@link NonRecursiveChildBlockType}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NonRecursiveChildBlockType".
 */
export type NonRecursiveChildBlockType =
  | 'SimpleTextChild'
  | 'RichTextChild'
  | 'ImageChild'
  | 'VideoChild'
  | 'IconChild'
  | 'SVGChild';
/**
 * Type: {@link BackdropChildSlug}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BackdropChildSlug".
 */
export type BackdropChildSlug = 'SVGChild';
/**
 * Type: {@link ChildrenWithTriggerActions}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChildrenWithTriggerActions".
 */
export type ChildrenWithTriggerActions = 'AtomicChild';
/**
 * Type: {@link ChildrenWithContentActions}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChildrenWithContentActions".
 */
export type ChildrenWithContentActions = 'AtomicChild' | 'SimpleTextChild';
/**
 * Type: {@link ChildrenWithActions}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChildrenWithActions".
 */
export type ChildrenWithActions = 'AtomicChild' | 'SimpleTextChild';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    AtomicChild: AtomicChild;
    SimpleTextChild: SimpleTextChild;
    RichTextChild: RichTextChild;
    ImageChild: ImageChild;
    VideoChild: VideoChild;
    IconChild: IconChild;
    SVGChild: SVGChild;
    ActSetCC: ActSetCC;
    ActCCToDA: ActCCToDA;
    ActSetTheme: ActSetTheme;
    ActResetForm: ActResetForm;
    ActDSSetBool: ActDSSetBool;
    ActSubmitForm: ActSubmitForm;
    ActDSBoolToDA: ActDSBoolToDA;
    ActDSTextToDA: ActDSTextToDA;
    ActDSCycleText: ActDSCycleText;
    ActFormErrorToDA: ActFormErrorToDA;
    ActSetPortalOpen: ActSetPortalOpen;
    ActFormStatusToDA: ActFormStatusToDA;
    FrlSimpleSlidingWindow: FrlSimpleSlidingWindow;
    FsCombineTwoFields: FsCombineTwoFields;
    FvIsUnique: FvIsUnique;
    IsTrimText: IsTrimText;
    IvContains: IvContains;
    IvDoesNotContain: IvDoesNotContain;
  };
  collections: {
    font: Font;
    icon: Icon;
    users: User;
    pages: Page;
    footer: Footer;
    header: Header;
    images: Image;
    favicons: Favicon;
    iconSet: IconSet;
    designSet: DesignSet;
    shortcutSet: ShortcutSet;
    posthogProperty: PosthogProperty;
    'mux-video': MuxVideo;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    font: FontSelect<false> | FontSelect<true>;
    icon: IconSelect<false> | IconSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    favicons: FaviconsSelect<false> | FaviconsSelect<true>;
    iconSet: IconSetSelect<false> | IconSetSelect<true>;
    designSet: DesignSetSelect<false> | DesignSetSelect<true>;
    shortcutSet: ShortcutSetSelect<false> | ShortcutSetSelect<true>;
    posthogProperty: PosthogPropertySelect<false> | PosthogPropertySelect<true>;
    'mux-video': MuxVideoSelect<false> | MuxVideoSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    tracking: Tracking;
    siteMetaData: SiteMetaDatum;
    draftStorage: DraftStorage;
    publishedStorage: PublishedStorage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    tracking: TrackingSelect<false> | TrackingSelect<true>;
    siteMetaData: SiteMetaDataSelect<false> | SiteMetaDataSelect<true>;
    draftStorage: DraftStorageSelect<false> | DraftStorageSelect<true>;
    publishedStorage: PublishedStorageSelect<false> | PublishedStorageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicChild".
 */
export interface AtomicChild {
  type: AtomicChildVariants;
  tagType?: AtomicTagType;
  buttonType?: AtomicButtonTypes;
  inputType?: AtomicInputTypes;
  backendForm?: string | null;
  formName?: string | null;
  inputName?: string | null;
  portalType?: AtomicButtonPortalTypes;
  portalName?: string | null;
  persisted?: boolean | null;
  linkType?: AtomicButtonLinkTypes;
  internalLink?: (string | null) | Page;
  externalLink?: string | null;
  download?: (string | null) | Image;
  email?: string | null;
  phone?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  ClassName?: string | null;
  children?: ChildBlocks;
  /**
   * Add atomic style classes or shortcuts here.
   */
  triggerClassName?: string | null;
  /**
   * Accessibility label for screen readers.
   */
  ariaLabel?: string | null;
  /**
   * Text specifically for screen readers. Required if no visible text is present.
   */
  screenReaderText?: string | null;
  triggerChildren?: ChildBlocks;
  triggerActions?: AllActions;
  contentActions?: AllActions;
  formRateLimitBlocks?: FormRateLimitBlocks;
  formSanitationBlocks?: FormSanitationBlocks;
  formValidationBlocks?: FormValidationBlocks;
  /**
   * If checked, this input field is required.
   */
  required?: boolean | null;
  inputSanitationBlocks?: InputSanitationBlocks;
  inputValidationBlocks?: InputValidationBlocks;
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  /**
   * The name of the input this label is associated with.
   */
  htmlFor?: string | null;
  formToastEnabled?: boolean | null;
  /**
   * Forms Loading Message
   */
  lm?: string | null;
  /**
   * Forms Default Success Message
   */
  sm?: string | null;
  /**
   * Forms Default Error Message
   */
  em?: string | null;
  anchor?: string | null;
  parameters?: string | null;
  prefetch?: boolean | null;
  newTab?: boolean | null;
  noOpener?: boolean | null;
  noReferrer?: boolean | null;
  replace?: boolean | null;
  scrollTo?: boolean | null;
  autocomplete?: AutocompleteOptions;
  textPlaceholder?: string | null;
  textDefault?: string | null;
  numberPlaceholder?: string | null;
  numberDefault?: number | null;
  checkboxDefault?: boolean | null;
  radioDefault?: boolean | null;
  radioValue: string;
  /**
   * Add atomic classes or shortcuts to the portal backdrop div here.
   */
  backdropClassName?: string | null;
  backdropChildren?: BackdropChildren;
  ds?: DialogSettings;
  pops?: PopoverSettings;
  triggerStaticDataAttributes?: StaticDataAttributes;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'AtomicChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Page;
  href?: string | null;
  /**
   * If unchecked, the page will not be indexed by search engines, and can only be viewed in admins live preview.
   */
  live: boolean;
  /**
   * Add atomic style classes or shortcuts here.
   */
  mainClassName?: string | null;
  children?: ChildBlocks;
  meta: PageSEO;
  storedAtomicClasses?: string[];
  storedAtomicForms?: StoredAtomicForm[];
  storedAtomicActions?: StoredAtomicActions;
  devMode: boolean;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  'apf-form'?: boolean | null;
  'apf-page'?: boolean | null;
  'apf-pages'?: boolean | null;
  'apf-actions'?: boolean | null;
  'apf-classes'?: boolean | null;
  'apf-seo'?: boolean | null;
  'apf-sitemap'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleTextChild".
 */
export interface SimpleTextChild {
  tagType: SimpleTextTagType;
  /**
   * Add atomic classes or shortcuts to the simple text element here.
   */
  ClassName?: string | null;
  /**
   * The name of the input this label is associated with.
   */
  htmlFor?: string | null;
  /**
   * The text content to display. Use {{data attribute name}} to display the data attributes value.
   */
  text: string;
  contentActions?: AllActions;
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SimpleTextChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "allActions".
 */
export interface AllActions {
  actionBlocks?: ActionBlocks;
  actions?: ActionBlockType[];
  runners?: Runners;
  attributers?: Attributers;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActSetCC".
 */
export interface ActSetCC {
  perform: CookieConsentPerform;
  acceptAll?: boolean | null;
  key?: CookieConsentPreferenceKeys;
  /**
   * If true, the value will be set as a data attribute on the element. Which can be used by atomic classes.
   */
  setDA?: boolean | null;
  changeKey?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActSetCC';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActCCToDA".
 */
export interface ActCCToDA {
  listen: CookieConsentListen;
  key?: CookieConsentPreferenceKeys;
  changeKey?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActCCToDA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActSetTheme".
 */
export interface ActSetTheme {
  perform: ThemePerform;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActSetTheme';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActResetForm".
 */
export interface ActResetForm {
  /**
   * The name of the front end form to reset.
   */
  formName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActResetForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActDSSetBool".
 */
export interface ActDSSetBool {
  /**
   * The name of the key to set. Use Kebab Case. (e.g. status-accepted)
   */
  key: string;
  /**
   * If true, the value will be persisted in the browser storage, and replace the initial value. Beware of FOUC is using these for initial visual state.
   */
  persisted?: boolean | null;
  /**
   * If true, the value will be set as a data attribute on the element. Which can be used by atomic classes.
   */
  setDA?: boolean | null;
  /**
   * The initial value to set the key to. Checked = true, Unchecked = false. First click set the opposite of this value.
   */
  initialValue?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActDSSetBool';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActSubmitForm".
 */
export interface ActSubmitForm {
  /**
   * The name of the front end form to submit.
   */
  formName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActSubmitForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActDSBoolToDA".
 */
export interface ActDSBoolToDA {
  /**
   * The name of the key to set. Use Kebab Case. (e.g. status-accepted)
   */
  key: string;
  changeKey?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActDSBoolToDA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActDSTextToDA".
 */
export interface ActDSTextToDA {
  /**
   * The name of the key to set. Use Kebab Case. (e.g. status-accepted)
   */
  key: string;
  changeKey?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActDSTextToDA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActDSCycleText".
 */
export interface ActDSCycleText {
  /**
   * The name of the key to set. Use Kebab Case. (e.g. status-accepted)
   */
  key: string;
  /**
   * If true, the value will be persisted in the browser storage, and replace the initial value. Beware of FOUC is using these for initial visual state.
   */
  persisted?: boolean | null;
  /**
   * If true, the value will be set as a data attribute on the element. Which can be used by atomic classes.
   */
  setDA?: boolean | null;
  textArray: {
    /**
     * The initial value to set the key to. Checked = true, Unchecked = false. First click set the opposite of this value.
     */
    initialValue?: boolean | null;
    /**
     * The value to set the key to.
     */
    value: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActDSCycleText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActFormErrorToDA".
 */
export interface ActFormErrorToDA {
  /**
   * The name of the front end form to use the response of.
   */
  formName?: string | null;
  /**
   * The name of the input to listen for changes on. If empty, defaults to using the form level message.
   */
  inputName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActFormErrorToDA';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActSetPortalOpen".
 */
export interface ActSetPortalOpen {
  /**
   * The name of the portal to toggle.
   */
  portal?: string | null;
  /**
   * If true, the value will be set as a data attribute on the element. Which can be used by atomic classes.
   */
  setDA?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActSetPortalOpen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActFormStatusToDA".
 */
export interface ActFormStatusToDA {
  /**
   * The name of the front end form to check the status of.
   */
  formName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ActFormStatusToDA';
}
/**
 * Type: {@link RunSetCC}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunSetCC".
 */
export interface RunSetCC {
  type: 'RunSetCC';
  values:
    | {
        perform: 'decline';
      }
    | {
        perform: 'preference';
        key: CookieConsentPreferenceKeys;
      }
    | {
        perform: 'accept';
        acceptAll?: boolean;
      };
}
/**
 * Type: {@link RunSetTheme}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunSetTheme".
 */
export interface RunSetTheme {
  type: 'RunSetTheme';
  perform: ThemePerform;
}
/**
 * Type: {@link RunCycleText}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunCycleText".
 */
export interface RunCycleText {
  type: 'RunCycleText';
  key: string;
  initialValue?: string | null;
  textArray: {
    value: string;
    initialValue?: boolean | null;
  }[];
  persisted?: boolean | null;
}
/**
 * Type: {@link RunSetBool}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunSetBool".
 */
export interface RunSetBool {
  type: 'RunSetBool';
  key: string;
  initialValue?: boolean | null;
  persisted?: boolean | null;
}
/**
 * Type: {@link RunResetForm}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunResetForm".
 */
export interface RunResetForm {
  type: 'RunResetForm';
  formName?: string | null;
}
/**
 * Type: {@link RunSubmitForm}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RunSubmitForm".
 */
export interface RunSubmitForm {
  type: 'RunSubmitForm';
  formName?: string | null;
}
/**
 * Type: {@link AttCCToDA}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttCCToDA".
 */
export interface AttCCToDA {
  type: 'AttCCToDA';
  listen:
    | {
        listen: 'preference';
        key: CookieConsentPreferenceKeys;
      }
    | {
        listen: 'accept';
      }
    | {
        listen: 'decline';
      }
    | {
        listen: 'hasConsented';
      }
    | {
        listen: 'previouslyConsented';
      };
  changeKey?: string | null;
}
/**
 * Type: {@link AttBoolToDA}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttBoolToDA".
 */
export interface AttBoolToDA {
  type: 'AttBoolToDA';
  key: string;
  changeKey?: string | null;
  persisted?: boolean | null;
  initialValue?: boolean | null;
}
/**
 * Type: {@link AttTextToDA}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttTextToDA".
 */
export interface AttTextToDA {
  type: 'AttTextToDA';
  key: string;
  persisted?: boolean | null;
  changeKey?: string | null;
  initialValue?: string | null;
}
/**
 * Type: {@link AttFormErrorToDA}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttFormErrorToDA".
 */
export interface AttFormErrorToDA {
  type: 'AttFormErrorToDA';
  key: string;
  inputName?: string | null;
}
/**
 * Type: {@link AttFormStatusToDA}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AttFormStatusToDA".
 */
export interface AttFormStatusToDA {
  type: 'AttFormStatusToDA';
  key: string;
  changeKey?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posthogProperty".
 */
export interface PosthogProperty {
  id: string;
  title: string;
  description?: string | null;
  /**
   * What this should be used for. e.g marketing, user flow, etc.
   */
  purpose: string;
  /**
   * The formal property name. e.g page_name
   */
  propertyFormal: string;
  /**
   * The obfuscated property name. e.g page_name_obfuscated
   */
  propertyObfuscated: string;
  /**
   * The formal value. e.g Home
   */
  valueFormal: string;
  /**
   * The obfuscated value. e.g Home_obfuscated
   */
  valueObfuscated: string;
  /**
   * Where this should be used. e.g page, component, global
   */
  location: 'page' | 'component' | 'global';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextChild".
 */
export interface RichTextChild {
  /**
   * Add the class 'prose' to apply tag based styles to rich text content. Supports suffixes '-sm', '-base', '-lg', '-xl', '-2xl'
   */
  ClassName?: string | null;
  richText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'RichTextChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageChild".
 */
export interface ImageChild {
  /**
   * Select the image to be displayed.
   */
  image: string | Image;
  /**
   * Select the stored version of the image you want to use. Leave blank for automatic optimization.
   */
  version?: ('thumbnail' | 'square' | 'small' | 'medium' | 'large' | 'xlarge' | 'og') | null;
  /**
   * Defaults to alt set on the image asset. But you can add an alt for this instance here.
   */
  alt?: string | null;
  /**
   * Classes are added directly to the nextImage component.
   */
  ClassName?: string | null;
  /**
   * Default false. If true, the asset will be pre-loaded and disable lazy loading.
   */
  priority?: boolean | null;
  /**
   * Default false. If true, will use the automatically generated blur data URL for the image.
   */
  blur?: boolean | null;
  /**
   * Default false. If true, will not optimize the image for the web. Best for tiny images like logos.
   */
  unoptimized?: boolean | null;
  /**
   * Default false. If true, the image will be resized to fill the parent container.
   */
  fill?: boolean | null;
  /**
   * Default is lazy. Use eager for images visible on load.
   */
  loading?: ('lazy' | 'eager') | null;
  /**
   * Default is async. Use sync for images visible on load.
   */
  decoding?: ('auto' | 'sync' | 'async') | null;
  /**
   * If not set, will default to image width. Example: "100vw" or "100px".
   */
  size?: string | null;
  /**
   * 0-100. Default is 75. Use 100 for best quality.
   */
  quality?: number | null;
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  alt?: string | null;
  blurDataUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoChild".
 */
export interface VideoChild {
  /**
   * It is recommended to use this inside a tag component that controls sizing, use the default value.
   */
  ClassName?: string | null;
  tagType: VideoTagType;
  video: string | MuxVideo;
  /**
   * Default is metadata. Controls when the video starts loading.
   */
  preload?: ('none' | 'metadata' | 'auto') | null;
  /**
   * Default is false. If true, the video will autoplay, which also forces muted to be true.
   */
  autoplay?: boolean | null;
  /**
   * Default is false. If true, the video will loop.
   */
  loop?: boolean | null;
  /**
   * Default is false. If true, the video will be muted.
   */
  muted?: boolean | null;
  /**
   * Default is false. If true, the video will not use the blur data URL.
   */
  disableBlur?: boolean | null;
  /**
   * Default is 0. The time in the video, the blur image will be generated from.
   */
  time?: number | null;
  /**
   * Default is 20. The blur amount of the video.
   */
  blur?: number | null;
  /**
   * Default is 1. The quality of the video.
   */
  quality?: number | null;
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'VideoChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mux-video".
 */
export interface MuxVideo {
  id: string;
  /**
   * A unique title for this video that will help you identify it later.
   */
  title: string;
  assetId?: string | null;
  duration?: number | null;
  /**
   * Pick a timestamp (in seconds) from the video to be used as the poster image. When unset, defaults to the middle of the video.
   */
  posterTimestamp?: number | null;
  aspectRatio?: string | null;
  maxWidth?: number | null;
  maxHeight?: number | null;
  playbackOptions?:
    | {
        playbackId?: string | null;
        playbackPolicy?: ('signed' | 'public') | null;
        playbackUrl?: string | null;
        posterUrl?: string | null;
        gifUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconChild".
 */
export interface IconChild {
  icon?: string | null;
  /**
   * If checked, the icon will be hidden to screen readers. This is useful if you want to use the icon for decorative purposes only.
   */
  ariaHidden?: boolean | null;
  /**
   * Styles applied directly on the svg. If left empty, defaults to 100% width and height.
   */
  ClassName?: string | null;
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'IconChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SVGChild".
 */
export interface SVGChild {
  /**
   * Add atomic classes or shortcuts to the svg element here.
   */
  ClassName?: string | null;
  /**
   * If true, the element will be hidden from screen readers.
   */
  ariaHidden?: boolean | null;
  /**
   * SVG viewbox attribute. Example: "0 0 24 24".
   */
  viewBox: string;
  /**
   * SVG fill attribute. Example: "currentColor" or "#000000".
   */
  fill?: string | null;
  /**
   * SVG content/path data.
   */
  contents: string;
  /**
   * Sets the components anchor ID, which can be used in anchor links.
   */
  cid?: string | null;
  staticDataAttributes?: StaticDataAttributes;
  contentPostHogProperty?: (string | PosthogProperty)[] | null;
  triggerPostHogProperty?: (string | PosthogProperty)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SVGChild';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageSEO".
 */
export interface PageSEO {
  title?: string | null;
  description?: string | null;
  /**
   * The pages Open Graph image. This will override the global Open Graph image.
   */
  image?: (string | null) | Image;
  /**
   * Overrides the global light favicon.
   */
  lightFavicon?: (string | null) | Favicon;
  /**
   * Overrides the global dark favicon.
   */
  darkFavicon?: (string | null) | Favicon;
  /**
   * Prevents the page from being indexed by search engines.
   */
  noIndex: boolean;
  /**
   * Priority of the page compared to other pages. 0-1. Default is 0.5. Home page should be 1.
   */
  priority?: number | null;
  /**
   * How often the page is updated. Defaults to monthly.
   */
  changeFrequency?: ('daily' | 'weekly' | 'monthly' | 'yearly' | 'never') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favicons".
 */
export interface Favicon {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoredAtomicForm".
 */
export interface StoredAtomicForm {
  id: string;
  sm?: string;
  em?: string;
  backendForm: string;
  sanitation?: FormSanitationBlocks;
  validation?: FormValidationBlocks;
  rateLimiting?: FormRateLimitBlocks;
  inputs?: StoredAtomicFormInput[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FsCombineTwoFields".
 */
export interface FsCombineTwoFields {
  firstFieldName: string;
  /**
   * Adds a string between the two fields. Defaults to a space.
   */
  addBetween?: string | null;
  secondFieldName: string;
  outputFieldName: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FsCombineTwoFields';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FvIsUnique".
 */
export interface FvIsUnique {
  fieldName: string;
  /**
   * The number of times the field can be used. It defaults to 1.
   */
  limit: number;
  /**
   * The message to display when the validation fails. Use {{inputName}} to display the input's value.
   */
  validationMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FvIsUnique';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FrlSimpleSlidingWindow".
 */
export interface FrlSimpleSlidingWindow {
  /**
   * If true, the rate limit trigger runs before validation. For normal forms its recommended to set this to false, as failed submissions due to validation errors will count towards the rate limit.
   */
  atStart: boolean;
  /**
   * The number of requests allowed per time period.
   */
  rateLimit: number;
  /**
   * The time period in minutes.
   */
  rateLimitPeriod: number;
  /**
   * The message to display when the validation fails. Use {{inputName}} to display the input's value.
   */
  validationMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FrlSimpleSlidingWindow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoredAtomicFormInput".
 */
export interface StoredAtomicFormInput {
  id: string;
  type: string;
  inputName: string;
  sanitationBlocks?: InputSanitationBlocks;
  validationBlocks?: InputValidationBlocks;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IsTrimText".
 */
export interface IsTrimText {
  trimType: 'beginning' | 'end' | 'both';
  /**
   * The characters to trim. Comma seperated list. Defaults to just removing spaces.
   */
  trimCharacters: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'IsTrimText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IvContains".
 */
export interface IvContains {
  containsValue: string;
  /**
   * The message to display when the validation fails. Use {{inputName}} to display the input's value.
   */
  validationMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'IvContains';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IvDoesNotContain".
 */
export interface IvDoesNotContain {
  doesNotContainValue?: string | null;
  /**
   * The message to display when the validation fails. Use {{inputName}} to display the input's value.
   */
  validationMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'IvDoesNotContain';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoredAtomicActions".
 */
export interface StoredAtomicActions {
  [k: string]: StoredAtomicAction;
}
/**
 * This interface was referenced by `StoredAtomicActions`'s JSON-Schema definition
 * via the `patternProperty` "^.*$".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoredAtomicAction".
 */
export interface StoredAtomicAction {
  id: string;
  runners?: Runners;
  attributers?: Attributers;
  actions: ActionBlockType[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DialogSettings".
 */
export interface DialogSettings {
  /**
   * If checked, the portal will be open by default.
   */
  defaultOpen?: boolean | null;
  /**
   * If checked, the dialog will be dismissible.
   */
  dismissible?: boolean | null;
  /**
   * If checked, the portal will remain in the DOM when hidden.
   */
  keepMounted?: boolean | null;
  modal?: TrapFocus;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PopoverSettings".
 */
export interface PopoverSettings {
  /**
   * If checked, the portal will be open by default.
   */
  defaultOpen?: boolean | null;
  /**
   * If checked, the popover will open on hover.
   */
  openOnHover?: boolean | null;
  /**
   * If checked, the popover will have an arrow.
   */
  hasArrow?: boolean | null;
  /**
   * If checked, the portal will remain in the DOM when hidden.
   */
  keepMounted?: boolean | null;
  modal?: TrapFocus;
  /**
   * The delay in milliseconds before the popover opens. Useful to adjust when open on hover is true.
   */
  delay?: number | null;
  /**
   * The delay in milliseconds before the popover closes.
   */
  closeDelay?: number | null;
  /**
   * If checked, the portal will be sticky to the top of the screen.
   */
  sticky?: boolean | null;
  /**
   * If checked, the portal will track the anchor of the parent element.
   */
  trackAnchor?: boolean | null;
  /**
   * The side of the portal.
   */
  side?: ('top' | 'bottom' | 'left' | 'right') | null;
  /**
   * The offset of the portal.
   */
  sideOffset?: number | null;
  /**
   * The alignment of the portal.
   */
  align?: ('center' | 'start' | 'end') | null;
  /**
   * The offset of the portal.
   */
  alignOffset?: number | null;
  /**
   * Determines which CSS position property to use.
   */
  positionMethod?: ('absolute' | 'fixed') | null;
  /**
   * The padding in pixels for the arrow.
   */
  arrowPadding?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font".
 */
export interface Font {
  id: string;
  title: string;
  family: GenericFontFamily;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icon".
 */
export interface Icon {
  id: string;
  optimized?: string | null;
  svgString?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  active: boolean;
  devMode: boolean;
  title: string;
  testPath?: (string | null) | Page;
  /**
   * Add atomic style classes or shortcuts here.
   */
  ClassName?: string | null;
  children?: ChildBlocks;
  storedAtomicClasses?: string[];
  storedAtomicForms?: StoredAtomicForm[];
  storedAtomicActions?: StoredAtomicActions;
  'apf-form'?: boolean | null;
  'apf-actions'?: boolean | null;
  'apf-classes'?: boolean | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  active: boolean;
  devMode: boolean;
  title: string;
  testPath?: (string | null) | Page;
  /**
   * Add atomic style classes or shortcuts here.
   */
  ClassName?: string | null;
  children?: ChildBlocks;
  storedAtomicClasses?: string[];
  storedAtomicForms?: StoredAtomicForm[];
  storedAtomicActions?: StoredAtomicActions;
  'apf-form'?: boolean | null;
  'apf-actions'?: boolean | null;
  'apf-classes'?: boolean | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iconSet".
 */
export interface IconSet {
  id: string;
  active: boolean;
  title: string;
  testPath?: (string | null) | Page;
  iconsArray?:
    | {
        /**
         * The name of the icon
         */
        name: string;
        /**
         * Select an icon
         */
        icon?: (string | null) | Icon;
        id?: string | null;
      }[]
    | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designSet".
 */
export interface DesignSet {
  id: string;
  active: boolean;
  title: string;
  testPath?: (string | null) | Page;
  minify: boolean;
  defaultTheme: 'light' | 'dark';
  /**
   * These are the atomic classes and shortcuts that are applied to the html element. Note that changing will unset the live previews selected theme(dark/light), ctrl + r will fix that.
   */
  htmlClassName?: string | null;
  /**
   * These are the atomic classes and shortcuts that are applied to the body element. Typically used for a background color.
   */
  bodyClassName?: string | null;
  /**
   * The wrapper goes around header, main, and footer. It supplies styles to the entire site. But is required for dialogs and popovers to work. Isolate will automatically be added to the beginning of the class name if not included.
   */
  wrapperClassName?: string | null;
  /**
   * Sets the value for the corresponding css variable.
   */
  defaults?: {
    spacing?: string | null;
    radius?: string | null;
  };
  variables?: TokenString;
  colors?: DesignSetColors;
  container?: TokenString;
  breakpoint?: TokenString;
  spacing?: TokenString;
  radius?: TokenString;
  font?: {
    sans?: (string | null) | Font;
    serif?: (string | null) | Font;
    mono?: (string | null) | Font;
    display?: (string | null) | Font;
  };
  text?:
    | {
        name: string;
        fontSize: string;
        lineHeight: string;
        id?: string | null;
      }[]
    | null;
  fontWeight?: TokenString;
  tracking?: TokenString;
  leading?: TokenString;
  textStrokeWidth?: TokenString;
  animation?:
    | {
        /**
         * The name of the animation used in class names fields. Capitals will be lowercased. Spaces will be replaced with hyphens (-). So type freely.
         */
        name: string;
        /**
         * The @keyframes information for the animation.
         */
        keyframes: string;
        /**
         * The length of the animation in seconds.
         */
        duration?: string | null;
        /**
         * Interpolation functions like linear/ease-in-out.
         */
        timingFns?: string | null;
        /**
         * Special properties like transform-origin and backface-visibility.
         */
        properties?: string | null;
        /**
         * The times the animation should play, either infinite or a number.
         */
        counts?: string | null;
        /**
         * The ease of the animation.
         */
        ease?: string | null;
        id?: string | null;
      }[]
    | null;
  ease?: TokenString;
  property?: TokenStringArray;
  aria: {
    value: string;
    id?: string | null;
  }[];
  blur?: TokenString;
  media?: TokenString;
  supports?: TokenString;
  perspective?: TokenString;
  shadow?: TokenStringArray;
  insetShadow?: TokenStringArray;
  dropShadow?: TokenStringArray;
  textShadow?: TokenStringArray;
  preflightStorage?: string | null;
  tokenStorage?: TokenStorage;
  body?: {
    light?: string | null;
    dark?: string | null;
  };
  headings?: {
    light?: string | null;
    dark?: string | null;
  };
  lead?: {
    light?: string | null;
    dark?: string | null;
  };
  links?: {
    light?: string | null;
    dark?: string | null;
  };
  bold?: {
    light?: string | null;
    dark?: string | null;
  };
  counters?: {
    light?: string | null;
    dark?: string | null;
  };
  bullets?: {
    light?: string | null;
    dark?: string | null;
  };
  hr?: {
    light?: string | null;
    dark?: string | null;
  };
  quotes?: {
    light?: string | null;
    dark?: string | null;
  };
  'quote-borders'?: {
    light?: string | null;
    dark?: string | null;
  };
  captions?: {
    light?: string | null;
    dark?: string | null;
  };
  kbd?: {
    light?: string | null;
    dark?: string | null;
  };
  'kbd-shadows'?: {
    light?: string | null;
    dark?: string | null;
  };
  code?: {
    light?: string | null;
    dark?: string | null;
  };
  'pre-code'?: {
    light?: string | null;
    dark?: string | null;
  };
  'pre-bg'?: {
    light?: string | null;
    dark?: string | null;
  };
  'th-borders'?: {
    light?: string | null;
    dark?: string | null;
  };
  'td-borders'?: {
    light?: string | null;
    dark?: string | null;
  };
  /**
   * This size applies to small screens and above
   */
  sm?:
    | {
        tag?: TypographySupportedTags;
        values?:
          | {
              cssSelector?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This size applies to base screens and above.
   */
  base?:
    | {
        tag?: TypographySupportedTags;
        values?:
          | {
              cssSelector?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This size applies to large screens and above.
   */
  lg?:
    | {
        tag?: TypographySupportedTags;
        values?:
          | {
              cssSelector?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  'apf-classes'?: boolean | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Type: {@link TokenStorage}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TokenStorage".
 */
export interface TokenStorage {
  font: RSS;
  aria: RSS;
  perspective: RSS;
  blur: RSS;
  media: RSS;
  supports: RSS;
  ease: RSS;
  property: RSS;
  container: RSS;
  breakpoint: RSS;
  spacing: RSS;
  radius: RSS;
  fontWeight: RSS;
  tracking: RSS;
  leading: RSS;
  textStrokeWidth: RSS;
  variables: RSS;
  shadow: RSSOSA;
  insetShadow: RSSOSA;
  dropShadow: RSSOSA;
  textShadow: RSSOSA;
  colors: UnoColors;
  animation: UnoThemeAnimation;
}
/**
 * Type: {@link RSS} Record<string, string>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RSS".
 */
export interface RSS {
  [k: string]: string;
}
/**
 * Type: {@link RSSOSA} Record<string, string | string[]>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RSSOSA".
 */
export interface RSSOSA {
  [k: string]: SOSA;
}
/**
 * Type: {@link UnoColors}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UnoColors".
 */
export interface UnoColors {
  [k: string]:
    | string
    | {
        [k: string]: string;
      };
}
/**
 * Type: {@link UnoThemeAnimation}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UnoThemeAnimation".
 */
export interface UnoThemeAnimation {
  category?: RSS;
  keyframes?: RSS;
  durations?: RSS;
  timingFns?: RSS;
  properties?: RSRSS;
  counts?: {
    [k: string]: string | number;
  };
}
/**
 * Type: {@link RSRSS} Record<string, Record<string, string>>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RSRSS".
 */
export interface RSRSS {
  [k: string]: RSS;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shortcutSet".
 */
export interface ShortcutSet {
  id: string;
  active: boolean;
  title: string;
  testPath?: (string | null) | Page;
  shortcuts: {
    /**
     * The name of the shortcut. This is used to identify the shortcut in the code.
     */
    name: string;
    /**
     * Add atomic style classes or shortcuts here.
     */
    ClassName?: string | null;
    id?: string | null;
  }[];
  /**
   * Default shortcuts are set in the project code at /src/collections/shortcutSets/defaults.ts
   */
  defaultShortcuts?:
    | {
        name: string;
        mod?: boolean | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        ClassName?: string | null;
        id?: string | null;
      }[]
    | null;
  'apf-classes'?: boolean | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'font';
        value: string | Font;
      } | null)
    | ({
        relationTo: 'icon';
        value: string | Icon;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'footer';
        value: string | Footer;
      } | null)
    | ({
        relationTo: 'header';
        value: string | Header;
      } | null)
    | ({
        relationTo: 'images';
        value: string | Image;
      } | null)
    | ({
        relationTo: 'favicons';
        value: string | Favicon;
      } | null)
    | ({
        relationTo: 'iconSet';
        value: string | IconSet;
      } | null)
    | ({
        relationTo: 'designSet';
        value: string | DesignSet;
      } | null)
    | ({
        relationTo: 'shortcutSet';
        value: string | ShortcutSet;
      } | null)
    | ({
        relationTo: 'posthogProperty';
        value: string | PosthogProperty;
      } | null)
    | ({
        relationTo: 'mux-video';
        value: string | MuxVideo;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font_select".
 */
export interface FontSelect<T extends boolean = true> {
  title?: T;
  family?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icon_select".
 */
export interface IconSelect<T extends boolean = true> {
  optimized?: T;
  svgString?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  href?: T;
  live?: T;
  mainClassName?: T;
  children?: T | {};
  meta?: T | PageSEOSelect<T>;
  storedAtomicClasses?: T;
  storedAtomicForms?: T;
  storedAtomicActions?: T;
  devMode?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  'apf-form'?: T;
  'apf-page'?: T;
  'apf-pages'?: T;
  'apf-actions'?: T;
  'apf-classes'?: T;
  'apf-seo'?: T;
  'apf-sitemap'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageSEO_select".
 */
export interface PageSEOSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  lightFavicon?: T;
  darkFavicon?: T;
  noIndex?: T;
  priority?: T;
  changeFrequency?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  active?: T;
  devMode?: T;
  title?: T;
  testPath?: T;
  ClassName?: T;
  children?: T | {};
  storedAtomicClasses?: T;
  storedAtomicForms?: T;
  storedAtomicActions?: T;
  'apf-form'?: T;
  'apf-actions'?: T;
  'apf-classes'?: T;
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  active?: T;
  devMode?: T;
  title?: T;
  testPath?: T;
  ClassName?: T;
  children?: T | {};
  storedAtomicClasses?: T;
  storedAtomicForms?: T;
  storedAtomicActions?: T;
  'apf-form'?: T;
  'apf-actions'?: T;
  'apf-classes'?: T;
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  blurDataUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favicons_select".
 */
export interface FaviconsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iconSet_select".
 */
export interface IconSetSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  testPath?: T;
  iconsArray?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designSet_select".
 */
export interface DesignSetSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  testPath?: T;
  minify?: T;
  defaultTheme?: T;
  htmlClassName?: T;
  bodyClassName?: T;
  wrapperClassName?: T;
  defaults?:
    | T
    | {
        spacing?: T;
        radius?: T;
      };
  variables?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        name?: T;
        light?: T;
        dark?: T;
        id?: T;
      };
  container?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  breakpoint?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  spacing?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  radius?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  font?:
    | T
    | {
        sans?: T;
        serif?: T;
        mono?: T;
        display?: T;
      };
  text?:
    | T
    | {
        name?: T;
        fontSize?: T;
        lineHeight?: T;
        id?: T;
      };
  fontWeight?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  tracking?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  leading?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  textStrokeWidth?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  animation?:
    | T
    | {
        name?: T;
        keyframes?: T;
        duration?: T;
        timingFns?: T;
        properties?: T;
        counts?: T;
        ease?: T;
        id?: T;
      };
  ease?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  property?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  aria?:
    | T
    | {
        value?: T;
        id?: T;
      };
  blur?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  media?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  supports?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  perspective?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  shadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  insetShadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  dropShadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  textShadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  preflightStorage?: T;
  tokenStorage?: T;
  body?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  headings?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  lead?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  links?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  bold?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  counters?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  bullets?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  hr?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  quotes?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  'quote-borders'?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  captions?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  kbd?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  'kbd-shadows'?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  code?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  'pre-code'?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  'pre-bg'?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  'th-borders'?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  'td-borders'?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  sm?:
    | T
    | {
        tag?: T;
        values?:
          | T
          | {
              cssSelector?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  base?:
    | T
    | {
        tag?: T;
        values?:
          | T
          | {
              cssSelector?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  lg?:
    | T
    | {
        tag?: T;
        values?:
          | T
          | {
              cssSelector?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  'apf-classes'?: T;
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shortcutSet_select".
 */
export interface ShortcutSetSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  testPath?: T;
  shortcuts?:
    | T
    | {
        name?: T;
        ClassName?: T;
        id?: T;
      };
  defaultShortcuts?:
    | T
    | {
        name?: T;
        mod?: T;
        ClassName?: T;
        id?: T;
      };
  'apf-classes'?: T;
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posthogProperty_select".
 */
export interface PosthogPropertySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  purpose?: T;
  propertyFormal?: T;
  propertyObfuscated?: T;
  valueFormal?: T;
  valueObfuscated?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mux-video_select".
 */
export interface MuxVideoSelect<T extends boolean = true> {
  title?: T;
  assetId?: T;
  duration?: T;
  posterTimestamp?: T;
  aspectRatio?: T;
  maxWidth?: T;
  maxHeight?: T;
  playbackOptions?:
    | T
    | {
        playbackId?: T;
        playbackPolicy?: T;
        playbackUrl?: T;
        posterUrl?: T;
        gifUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  /**
   * Settings for the draft version of the website.
   */
  draft: {
    /**
     * The version of the websites persistent data. Changing this will reset the store, except for the cookie consent preferences. Use this when you change actions and things aren't working as expected.
     */
    storeVersion: number;
  };
  /**
   * Settings for the published version of the website.
   */
  published: {
    /**
     * The version of the websites persistent data. Changing this will reset the store, except for the cookie consent preferences. Use this when you change actions and things aren't working as expected.
     */
    storeVersion: number;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking".
 */
export interface Tracking {
  id: string;
  googleTagManagerEnabled?: boolean | null;
  postHogEnabled?: boolean | null;
  vercelAnalyticsEnabled?: boolean | null;
  googleTagManagerId?: string | null;
  postHogPublicKey: string;
  postHogHost: string;
  enableAutoCapture?: boolean | null;
  disableSessionRecording?: boolean | null;
  disableSurveys?: boolean | null;
  capturePerformance?: boolean | null;
  postHogAutoCaptureSettings?: {
    urlAllowList?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    urlIgnoreList?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteMetaData".
 */
export interface SiteMetaDatum {
  id: string;
  siteName?: string | null;
  fallbackSiteDescription?: string | null;
  fallbackOGImage?: (string | null) | Image;
  /**
   * Sets the favicon for the site.
   */
  fallbackLightFavicon?: (string | null) | Favicon;
  /**
   * Sets the favicon for the site.
   */
  fallbackDarkFavicon?: (string | null) | Favicon;
  'apf-siteMetadata'?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "draftStorage".
 */
export interface DraftStorage {
  id: string;
  cssSize: number;
  layoutCSS: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishedStorage".
 */
export interface PublishedStorage {
  id: string;
  cssSize: number;
  layoutCSS: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  draft?:
    | T
    | {
        storeVersion?: T;
      };
  published?:
    | T
    | {
        storeVersion?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking_select".
 */
export interface TrackingSelect<T extends boolean = true> {
  googleTagManagerEnabled?: T;
  postHogEnabled?: T;
  vercelAnalyticsEnabled?: T;
  googleTagManagerId?: T;
  postHogPublicKey?: T;
  postHogHost?: T;
  enableAutoCapture?: T;
  disableSessionRecording?: T;
  disableSurveys?: T;
  capturePerformance?: T;
  postHogAutoCaptureSettings?:
    | T
    | {
        urlAllowList?:
          | T
          | {
              url?: T;
              id?: T;
            };
        urlIgnoreList?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteMetaData_select".
 */
export interface SiteMetaDataSelect<T extends boolean = true> {
  siteName?: T;
  fallbackSiteDescription?: T;
  fallbackOGImage?: T;
  fallbackLightFavicon?: T;
  fallbackDarkFavicon?: T;
  'apf-siteMetadata'?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "draftStorage_select".
 */
export interface DraftStorageSelect<T extends boolean = true> {
  cssSize?: T;
  layoutCSS?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishedStorage_select".
 */
export interface PublishedStorageSelect<T extends boolean = true> {
  cssSize?: T;
  layoutCSS?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'footer';
          value: string | Footer;
        } | null)
      | ({
          relationTo: 'header';
          value: string | Header;
        } | null)
      | ({
          relationTo: 'iconSet';
          value: string | IconSet;
        } | null)
      | ({
          relationTo: 'designSet';
          value: string | DesignSet;
        } | null)
      | ({
          relationTo: 'shortcutSet';
          value: string | ShortcutSet;
        } | null);
    global?: ('settings' | 'tracking' | 'siteMetaData') | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicRegistry".
 */
export interface AtomicRegistry {
  RSS: RSS;
  SOSA: SOSA;
  RSRSS: RSRSS;
  RSSOSA: RSSOSA;
  UnoColors: UnoColors;
  DesignSetColors: DesignSetColors;
  TokenString?: TokenString;
  TokenStringArray?: TokenStringArray;
  UnoThemeAnimation: UnoThemeAnimation;
  TokenStorage: TokenStorage;
  CollectionThatUsesAtomicHookSlug: CollectionThatUsesAtomicHookSlug;
  CollectionWithStoredAtomicClassesSlug: CollectionWithStoredAtomicClassesSlug;
  CollectionThatUsesCSSProcessorSlug: CollectionThatUsesCSSProcessorSlug;
  CollectionWithStoredAtomicFormsSlug: CollectionWithStoredAtomicFormsSlug;
  CollectionWithStoredAtomicActionsSlug: CollectionWithStoredAtomicActionsSlug;
  ThemeKeys: ThemeKeys;
  ThemeListen: ThemeListen;
  ThemePerform: ThemePerform;
  CookieConsentPreferenceKeys: CookieConsentPreferenceKeys;
  CookieConsentListen: CookieConsentListen;
  CookieConsentPerform: CookieConsentPerform;
  ActionBlockType: ActionBlockType;
  RunSetCC: RunSetCC;
  RunSetTheme: RunSetTheme;
  RunResetForm: RunResetForm;
  RunSetBool: RunSetBool;
  RunSubmitForm: RunSubmitForm;
  RunCycleText: RunCycleText;
  Runner: Runner;
  Runners: Runners;
  RunnerType: RunnerType;
  AttCCToDA: AttCCToDA;
  AttBoolToDA: AttBoolToDA;
  AttTextToDA: AttTextToDA;
  AttFormErrorToDA: AttFormErrorToDA;
  AttFormStatusToDA: AttFormStatusToDA;
  Attributer: Attributer;
  Attributers: Attributers;
  AttributerType: AttributerType;
  InputSanitationBlockType: InputSanitationBlockType;
  InputValidationBlockType: InputValidationBlockType;
  FormRateLimitBlockType: FormRateLimitBlockType;
  FormSanitationBlockType: FormSanitationBlockType;
  FormValidationBlockType: FormValidationBlockType;
  ChildBlockType: ChildBlockType;
  NonRecursiveChildBlockType: NonRecursiveChildBlockType;
  BackdropChildSlug: BackdropChildSlug;
  ChildrenWithTriggerActions: ChildrenWithTriggerActions;
  ChildrenWithContentActions: ChildrenWithContentActions;
  ChildrenWithActions: ChildrenWithActions;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}