// AUTO-GENERATED by @pro-laico/core/scripts/appendPayloadAugment.mjs — do not edit by hand.
// Regenerated whenever `pnpm generate:types` runs.

import type * as G from './payload-types'

declare module '@pro-laico/core' {
  interface PayloadAugment {
    AtomicRegistry: G.AtomicRegistry
    CollectionThatUsesCSSProcessorSlug: G.CollectionThatUsesCSSProcessorSlug
    CollectionWithStoredAtomicClassesSlug: G.CollectionWithStoredAtomicClassesSlug
    DesignSet: G.DesignSet
    Font: G.Font
    Footer: G.Footer
    GeneratedImage: G.GeneratedImage
    Header: G.Header
    Icon: G.Icon
    IconSet: G.IconSet
    Image: G.Image
    Page: G.Page
    ShortcutSet: G.ShortcutSet
    SiteMetaDatum: G.SiteMetaDatum
    Tracking: G.Tracking
  }
}
