// AUTO-GENERATED by @pro-laico/ap-types/scripts/appendPayloadAugment.mjs — do not edit by hand.
// Regenerated whenever `pnpm generate:types` runs.

import type * as G from './payload-types'

declare module '@pro-laico/ap-types' {
  interface PayloadAugment {
    Icon: G.Icon
    IconSet: G.IconSet
  }
}
