#!/usr/bin/env node
/**
 * Generates a `payload-types.augment.d.ts` sibling next to a consumer
 * project's generated `payload-types.ts`. The augment file wires the
 * project's concrete types into the single shared `PayloadAugment` interface
 * declared in `@pro-laico/ap-core`, so every domain package's stubs
 * (Page, Icon, Form, ActionBlocks, …) resolve to project-specific shapes
 * instead of permissive `Get<>` fallbacks.
 *
 * Discovery: scans every `@pro-laico/*` package in the consumer's
 * `node_modules` for a marker file `src/types/payload-augment.ts`. Each line
 * matching `^export type X = Get<` contributes one `X` to the mapping (only
 * if the project's generated file actually exports `X`).
 *
 * Why a separate file: inside `declare module 'X' { … }`, identifiers resolve
 * in module X's scope, not the surrounding file's. So we need an outer-scope
 * `import type { Page } from './payload-types'` to reference the concrete
 * types — which means a file separate from payload-types.ts itself.
 *
 * Usage (from a consumer project):
 *   ap-core-augment-types                  # defaults to ./src/payload-types.ts
 *   ap-core-augment-types path/to/file.ts  # explicit path (relative to cwd)
 */
import fs from 'node:fs'
import path from 'node:path'

const generatedPath = path.resolve(process.cwd(), process.argv[2] || 'src/payload-types.ts')
const augmentPath = path.join(path.dirname(generatedPath), 'payload-types.augment.d.ts')
const scopeDir = path.join(process.cwd(), 'node_modules', '@pro-laico')

if (!fs.existsSync(generatedPath)) {
  console.error(`[augment] generated types file not found at ${generatedPath}`)
  process.exit(1)
}
if (!fs.existsSync(scopeDir)) {
  console.error(`[augment] @pro-laico packages directory not found at ${scopeDir}`)
  process.exit(1)
}

const stubFiles = fs
  .readdirSync(scopeDir)
  .map((name) => path.join(scopeDir, name, 'src', 'types', 'payload-augment.ts'))
  .filter((p) => fs.existsSync(p))

const stubNames = new Set()
for (const file of stubFiles) {
  const content = fs.readFileSync(file, 'utf8')
  for (const m of content.matchAll(/^export type ([A-Za-z][A-Za-z0-9_]*) = Get</gm)) {
    stubNames.add(m[1])
  }
}

const generatedContent = fs.readFileSync(generatedPath, 'utf8')
const exportedNames = new Set(
  Array.from(generatedContent.matchAll(/^export (?:type|interface) ([A-Za-z][A-Za-z0-9_]*)\b/gm)).map((m) => m[1]),
)

// Strip any prior augmentation block that may have been written into
// payload-types.ts during the earlier single-file experiment.
const SENTINEL_START = '// ===== BEGIN @pro-laico/ap-core augmentation (auto-generated) ====='
const SENTINEL_END = '// ===== END @pro-laico/ap-core augmentation ====='
if (generatedContent.includes(SENTINEL_START)) {
  const cleaned = generatedContent.replace(new RegExp(`\\n${SENTINEL_START}[\\s\\S]*?${SENTINEL_END}\\n?`, 'g'), '')
  fs.writeFileSync(generatedPath, cleaned.trimEnd() + '\n')
}

const mappable = Array.from(stubNames).filter((name) => exportedNames.has(name)).sort()
const mappings = mappable.map((name) => `    ${name}: G.${name}`).join('\n')

const file = `// AUTO-GENERATED by @pro-laico/ap-core/scripts/appendPayloadAugment.mjs — do not edit by hand.
// Regenerated whenever \`pnpm generate:types\` runs.

import type * as G from './payload-types'

declare module '@pro-laico/ap-core' {
  interface PayloadAugment {
${mappings}
  }
}
`

fs.writeFileSync(augmentPath, file)
console.log(`[augment] wrote ${path.relative(process.cwd(), augmentPath)} (${mappable.length} types from ${stubFiles.length} packages)`)
