// Generated by @pro-laico/fonts to wire your fonts into next/font/local.
// Shipped empty so the app runs before any fonts are downloaded — run
// `pnpm setup:fonts` (or `generate:fonts`) to rewrite it with your active fonts.
const fonts = {}
export default fonts
