// DO NOT EDIT MANUALLY. THIS FILE IS AUTOMATICALLY GENERATED.

import localFont from 'next/font/local'

const fontSans = localFont({ src: [{ path: '../../public/fonts/sans-1-1000.woff2', weight: '1 1000', style: 'normal' }], variable: '--font-setSans' })

const fonts = { fontSans }
export default fonts
