/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GenericFontFamily".
 */
export type GenericFontFamily = 'sans' | 'serif' | 'mono' | 'display';
/**
 * Type: {@link TokenString}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TokenString".
 */
export type TokenString =
  | {
      name: string;
      value: string;
    }[]
  | null;
/**
 * Type: {@link DesignSetColors}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DesignSetColors".
 */
export type DesignSetColors = {
  name: string;
  light: string;
  dark: string;
}[];
/**
 * Type: {@link TokenStringArray}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TokenStringArray".
 */
export type TokenStringArray =
  | {
      name: string;
      values: {
        value: string;
      }[];
    }[]
  | null;
/**
 * This size applies to large screens and above with "prose prose-lg".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TypographyStyles".
 */
export type TypographyStyles =
  | {
      tag: TypographySupportedTags;
      /**
       * Optionally add a psuedo-class (e.g., :hover, :focus, etc.) to target specific states.
       */
      psuedoClass?: string | null;
      values?:
        | {
            cssSelector: string;
            value: string;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[]
  | null;
/**
 * Select the tag the nested styles will apply to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TypographySupportedTags".
 */
export type TypographySupportedTags =
  | 'headings'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'th'
  | 'p'
  | 'a'
  | 'blockquote'
  | 'figure'
  | 'figcaption'
  | 'strong'
  | 'em'
  | 'kbd'
  | 'code'
  | 'pre'
  | 'ol'
  | 'ul'
  | 'li'
  | 'table'
  | 'thead'
  | 'tr'
  | 'td'
  | 'img'
  | 'video'
  | 'hr';
/**
 * Type: {@link SOSA} String | String[]
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SOSA".
 */
export type SOSA = string | string[];
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    font: Font;
    designSet: DesignSet;
    shortcutSet: ShortcutSet;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    font: FontSelect<false> | FontSelect<true>;
    designSet: DesignSetSelect<false> | DesignSetSelect<true>;
    shortcutSet: ShortcutSetSelect<false> | ShortcutSetSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    draftStorage: DraftStorage;
    publishedStorage: PublishedStorage;
  };
  globalsSelect: {
    draftStorage: DraftStorageSelect<false> | DraftStorageSelect<true>;
    publishedStorage: PublishedStorageSelect<false> | PublishedStorageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The path this page renders at, e.g. `/`.
   */
  href: string;
  live: boolean;
  /**
   * Add atomic style classes or shortcuts here.
   */
  mainClassName?: string | null;
  layout?: (HeroBlock | ButtonRowBlock | CardGridBlock | ProseBlock | PaletteBlock)[] | null;
  storedAtomicClasses?: string[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  sectionClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  eyebrowClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  headingClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  subheadingClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  buttonsClassName?: string | null;
  buttons?:
    | {
        label: string;
        href?: string | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        buttonClassName?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock".
 */
export interface ButtonRowBlock {
  heading?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  headingClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  rowClassName?: string | null;
  buttons?:
    | {
        label: string;
        href?: string | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        buttonClassName?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buttonRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  heading?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  headingClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  gridClassName?: string | null;
  cards?:
    | {
        title: string;
        body?: string | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        cardClassName?: string | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        cardTitleClassName?: string | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        cardBodyClassName?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock".
 */
export interface ProseBlock {
  heading?: string | null;
  /**
   * Plain text. Blank lines separate paragraphs.
   */
  content?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  proseClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PaletteBlock".
 */
export interface PaletteBlock {
  heading?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  headingClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  gridClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  swatchClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  swatchBoxClassName?: string | null;
  /**
   * Add atomic style classes or shortcuts here.
   */
  swatchLabelClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'palette';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font".
 */
export interface Font {
  id: number;
  title: string;
  family: GenericFontFamily;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designSet".
 */
export interface DesignSet {
  id: number;
  active: boolean;
  title: string;
  testPath?: (number | null) | Page;
  minify: boolean;
  defaultTheme: 'light' | 'dark';
  /**
   * These are the atomic classes and shortcuts that are applied to the html element. Note that changing will unset the live previews selected theme(dark/light), ctrl + r will fix that.
   */
  htmlClassName?: string | null;
  /**
   * These are the atomic classes and shortcuts that are applied to the body element. Typically used for a background color.
   */
  bodyClassName?: string | null;
  /**
   * The wrapper goes around header, main, and footer. It supplies styles to the entire site. But is required for dialogs and popovers to work. Isolate will automatically be added to the beginning of the class name if not included.
   */
  wrapperClassName?: string | null;
  /**
   * Sets the value for the corresponding css variable.
   */
  defaults?: {
    spacing?: string | null;
    radius?: string | null;
  };
  variables?: TokenString;
  colors?: DesignSetColors;
  container?: TokenString;
  breakpoint?: TokenString;
  spacing?: TokenString;
  radius?: TokenString;
  font?: {
    sans?: (number | null) | Font;
    serif?: (number | null) | Font;
    mono?: (number | null) | Font;
    display?: (number | null) | Font;
  };
  text?:
    | {
        name: string;
        fontSize: string;
        lineHeight: string;
        id?: string | null;
      }[]
    | null;
  fontWeight?: TokenString;
  tracking?: TokenString;
  leading?: TokenString;
  textStrokeWidth?: TokenString;
  animation?:
    | {
        /**
         * The name of the animation used in class names fields. Capitals will be lowercased. Spaces will be replaced with hyphens (-). So type freely.
         */
        name: string;
        /**
         * The @keyframes information for the animation.
         */
        keyframes: string;
        /**
         * The length of the animation in seconds.
         */
        duration?: string | null;
        /**
         * Interpolation functions like linear/ease-in-out.
         */
        timingFns?: string | null;
        /**
         * Special properties like transform-origin and backface-visibility.
         */
        properties?: string | null;
        /**
         * The times the animation should play, either infinite or a number.
         */
        counts?: string | null;
        /**
         * The ease of the animation.
         */
        ease?: string | null;
        id?: string | null;
      }[]
    | null;
  ease?: TokenString;
  property?: TokenStringArray;
  aria: {
    value: string;
    id?: string | null;
  }[];
  blur?: TokenString;
  media?: TokenString;
  supports?: TokenString;
  perspective?: TokenString;
  shadow?: TokenStringArray;
  insetShadow?: TokenStringArray;
  dropShadow?: TokenStringArray;
  textShadow?: TokenStringArray;
  proseColors: ProseColors;
  proseStyles?: {
    default?: TypographyStyles;
    sm?: TypographyStyles;
    base?: TypographyStyles;
    lg?: TypographyStyles;
  };
  preflightStorage?: string | null;
  tokenStorage?: TokenStorage;
  proseDefaultStorage?: RSRSS;
  prosesmStorage?: RSRSS;
  proseBaseStorage?: RSRSS;
  proselgStorage?: RSRSS;
  proseColorStorage?: ProseColorStorage;
  'apf-classes'?: boolean | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseColors".
 */
export interface ProseColors {
  body: ProseColorField;
  headings: ProseColorField;
  lead: ProseColorField;
  links: ProseColorField;
  bold: ProseColorField;
  counters: ProseColorField;
  bullets: ProseColorField;
  hr: ProseColorField;
  quotes: ProseColorField;
  'quote-borders': ProseColorField;
  captions: ProseColorField;
  kbd: ProseColorField;
  'kbd-shadows': ProseColorField;
  code: ProseColorField;
  'pre-code': ProseColorField;
  'pre-bg': ProseColorField;
  'th-borders': ProseColorField;
  'td-borders': ProseColorField;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseColorField".
 */
export interface ProseColorField {
  light: string;
  dark: string;
}
/**
 * Type: {@link TokenStorage}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TokenStorage".
 */
export interface TokenStorage {
  font: RSS;
  aria: RSS;
  perspective: RSS;
  blur: RSS;
  media: RSS;
  supports: RSS;
  ease: RSS;
  property: RSS;
  container: RSS;
  breakpoint: RSS;
  spacing: RSS;
  radius: RSS;
  fontWeight: RSS;
  tracking: RSS;
  leading: RSS;
  textStrokeWidth: RSS;
  variables: RSS;
  shadow: RSSOSA;
  insetShadow: RSSOSA;
  dropShadow: RSSOSA;
  textShadow: RSSOSA;
  colors: UnoColors;
  animation: UnoThemeAnimation;
}
/**
 * Type: {@link RSS} Record<string, string>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RSS".
 */
export interface RSS {
  [k: string]: string;
}
/**
 * Type: {@link RSSOSA} Record<string, string | string[]>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RSSOSA".
 */
export interface RSSOSA {
  [k: string]: SOSA;
}
/**
 * Type: {@link UnoColors}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UnoColors".
 */
export interface UnoColors {
  [k: string]:
    | string
    | {
        [k: string]: string;
      };
}
/**
 * Type: {@link UnoThemeAnimation}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UnoThemeAnimation".
 */
export interface UnoThemeAnimation {
  category?: RSS;
  keyframes?: RSS;
  durations?: RSS;
  timingFns?: RSS;
  properties?: RSRSS;
  counts?: {
    [k: string]: string | number;
  };
}
/**
 * Type: {@link RSRSS} Record<string, Record<string, string>>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RSRSS".
 */
export interface RSRSS {
  [k: string]: RSS;
}
/**
 * Type: {@link ProseColorStorage}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseColorStorage".
 */
export interface ProseColorStorage {
  [k: string]: [] | [string] | [string, string];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shortcutSet".
 */
export interface ShortcutSet {
  id: number;
  active: boolean;
  title: string;
  testPath?: (number | null) | Page;
  shortcuts: {
    /**
     * The name of the shortcut. This is used to identify the shortcut in the code.
     */
    name: string;
    /**
     * Add atomic style classes or shortcuts here.
     */
    ClassName?: string | null;
    id?: string | null;
  }[];
  /**
   * Default shortcut rows come from `defaultShortcuts` on `stylesPlugin({ shortcutSet: { defaultShortcuts: [...] } })`.
   */
  defaultShortcuts?:
    | {
        name: string;
        mod?: boolean | null;
        /**
         * Add atomic style classes or shortcuts here.
         */
        ClassName?: string | null;
        id?: string | null;
      }[]
    | null;
  'apf-classes'?: boolean | null;
  'apf-active'?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'font';
        value: number | Font;
      } | null)
    | ({
        relationTo: 'designSet';
        value: number | DesignSet;
      } | null)
    | ({
        relationTo: 'shortcutSet';
        value: number | ShortcutSet;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  href?: T;
  live?: T;
  mainClassName?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        buttonRow?: T | ButtonRowBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        prose?: T | ProseBlockSelect<T>;
        palette?: T | PaletteBlockSelect<T>;
      };
  storedAtomicClasses?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  sectionClassName?: T;
  eyebrowClassName?: T;
  headingClassName?: T;
  subheadingClassName?: T;
  buttonsClassName?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        buttonClassName?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonRowBlock_select".
 */
export interface ButtonRowBlockSelect<T extends boolean = true> {
  heading?: T;
  headingClassName?: T;
  rowClassName?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        buttonClassName?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  heading?: T;
  headingClassName?: T;
  gridClassName?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        cardClassName?: T;
        cardTitleClassName?: T;
        cardBodyClassName?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseBlock_select".
 */
export interface ProseBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  proseClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PaletteBlock_select".
 */
export interface PaletteBlockSelect<T extends boolean = true> {
  heading?: T;
  headingClassName?: T;
  gridClassName?: T;
  swatchClassName?: T;
  swatchBoxClassName?: T;
  swatchLabelClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "font_select".
 */
export interface FontSelect<T extends boolean = true> {
  title?: T;
  family?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designSet_select".
 */
export interface DesignSetSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  testPath?: T;
  minify?: T;
  defaultTheme?: T;
  htmlClassName?: T;
  bodyClassName?: T;
  wrapperClassName?: T;
  defaults?:
    | T
    | {
        spacing?: T;
        radius?: T;
      };
  variables?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        name?: T;
        light?: T;
        dark?: T;
        id?: T;
      };
  container?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  breakpoint?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  spacing?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  radius?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  font?:
    | T
    | {
        sans?: T;
        serif?: T;
        mono?: T;
        display?: T;
      };
  text?:
    | T
    | {
        name?: T;
        fontSize?: T;
        lineHeight?: T;
        id?: T;
      };
  fontWeight?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  tracking?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  leading?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  textStrokeWidth?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  animation?:
    | T
    | {
        name?: T;
        keyframes?: T;
        duration?: T;
        timingFns?: T;
        properties?: T;
        counts?: T;
        ease?: T;
        id?: T;
      };
  ease?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  property?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  aria?:
    | T
    | {
        value?: T;
        id?: T;
      };
  blur?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  media?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  supports?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  perspective?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  shadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  insetShadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  dropShadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  textShadow?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  proseColors?: T | ProseColorsSelect<T>;
  proseStyles?:
    | T
    | {
        default?: T | TypographyStylesSelect<T>;
        sm?: T | TypographyStylesSelect<T>;
        base?: T | TypographyStylesSelect<T>;
        lg?: T | TypographyStylesSelect<T>;
      };
  preflightStorage?: T;
  tokenStorage?: T;
  proseDefaultStorage?: T;
  prosesmStorage?: T;
  proseBaseStorage?: T;
  proselgStorage?: T;
  proseColorStorage?: T;
  'apf-classes'?: T;
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseColors_select".
 */
export interface ProseColorsSelect<T extends boolean = true> {
  body?: T | ProseColorFieldSelect<T>;
  headings?: T | ProseColorFieldSelect<T>;
  lead?: T | ProseColorFieldSelect<T>;
  links?: T | ProseColorFieldSelect<T>;
  bold?: T | ProseColorFieldSelect<T>;
  counters?: T | ProseColorFieldSelect<T>;
  bullets?: T | ProseColorFieldSelect<T>;
  hr?: T | ProseColorFieldSelect<T>;
  quotes?: T | ProseColorFieldSelect<T>;
  'quote-borders'?: T | ProseColorFieldSelect<T>;
  captions?: T | ProseColorFieldSelect<T>;
  kbd?: T | ProseColorFieldSelect<T>;
  'kbd-shadows'?: T | ProseColorFieldSelect<T>;
  code?: T | ProseColorFieldSelect<T>;
  'pre-code'?: T | ProseColorFieldSelect<T>;
  'pre-bg'?: T | ProseColorFieldSelect<T>;
  'th-borders'?: T | ProseColorFieldSelect<T>;
  'td-borders'?: T | ProseColorFieldSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProseColorField_select".
 */
export interface ProseColorFieldSelect<T extends boolean = true> {
  light?: T;
  dark?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TypographyStyles_select".
 */
export interface TypographyStylesSelect<T extends boolean = true> {
  tag?: T;
  psuedoClass?: T;
  values?:
    | T
    | {
        cssSelector?: T;
        value?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shortcutSet_select".
 */
export interface ShortcutSetSelect<T extends boolean = true> {
  active?: T;
  title?: T;
  testPath?: T;
  shortcuts?:
    | T
    | {
        name?: T;
        ClassName?: T;
        id?: T;
      };
  defaultShortcuts?:
    | T
    | {
        name?: T;
        mod?: T;
        ClassName?: T;
        id?: T;
      };
  'apf-classes'?: T;
  'apf-active'?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "draftStorage".
 */
export interface DraftStorage {
  id: number;
  cssSize: number;
  layoutCSS: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishedStorage".
 */
export interface PublishedStorage {
  id: number;
  cssSize: number;
  layoutCSS: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "draftStorage_select".
 */
export interface DraftStorageSelect<T extends boolean = true> {
  cssSize?: T;
  layoutCSS?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishedStorage_select".
 */
export interface PublishedStorageSelect<T extends boolean = true> {
  cssSize?: T;
  layoutCSS?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'designSet';
          value: number | DesignSet;
        } | null)
      | ({
          relationTo: 'shortcutSet';
          value: number | ShortcutSet;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AtomicRegistry".
 */
export interface AtomicRegistry {
  RSS: RSS;
  SOSA: SOSA;
  RSRSS: RSRSS;
  RSSOSA: RSSOSA;
  TokenString?: TokenString;
  TokenStringArray?: TokenStringArray;
  UnoThemeAnimation: UnoThemeAnimation;
  UnoColors: UnoColors;
  DesignSetColors: DesignSetColors;
  TokenStorage: TokenStorage;
  ProseColorStorage: ProseColorStorage;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}