export { extractFonts } from './extractFonts'
export { exportFontsEndpoint } from './endpoints/exportFonts'
export { fontUploadField } from './fields/font'

export { createFontCollection, Font, FontUploaderPath } from './collections/font'
export type { CreateFontCollectionOptions } from './collections/font'
export { createFontFileCollection, FontFile, FONT_FILE_SLUG } from './collections/fontFile'
export type { CreateFontFileCollectionOptions, FontOptimizeConfig } from './collections/fontFile'
export { createFontOriginalCollection, FontOriginal, FONT_ORIGINAL_SLUG } from './collections/fontOriginal'
export { optimizeFontHook, cleanupOriginalHook, cleanupFontFilesHook, resolveCharsetText } from './hooks/optimizeFont'
export type { OptimizeFontHookOptions } from './hooks/optimizeFont'
export { uniqueWeightHook } from './hooks/uniqueWeight'
export { processPendingFontFiles, deleteDereferencedFontFiles } from './hooks/pendingFontFiles'

export { default, fontsPlugin } from './plugin'
export type { FontsPluginOptions, FontsOptimizeOption } from './plugin'
