import { PayloadSDK } from '@payloadcms/sdk'
import type { Font } from '@pro-laico/fonts/schema'
import dotenv from 'dotenv'
import fs from 'node:fs'
import https from 'node:https'
import path from 'node:path'

const colors = {
  blue: (t: string) => `\x1b[34m${t}\x1b[0m`,
  green: (t: string) => `\x1b[32m${t}\x1b[0m`,
  red: (t: string) => `\x1b[31m${t}\x1b[0m`,
  orange: (t: string) => `\x1b[33m${t}\x1b[0m`,
}

type GenericFontFamily = 'sans' | 'serif' | 'mono' | 'display'

type FontExtensions = Record<GenericFontFamily, string>

export type RunDownloadFontsOptions = {
  /** Directory for downloaded font files. Default `./public/fonts` or `ATOMIC_FONTS_OUTPUT_DIR`. */
  fontsOutputDir?: string
  /** Generated `next/font/local` module path. Default `./src/app/definition.ts` or `ATOMIC_FONTS_DEFINITION_FILE`. */
  definitionFile?: string
  /** Dotenv file to load before reading env. Default `./.env` or `ATOMIC_FONTS_ENV_FILE`. */
  envFile?: string
  /**
   * `src` path passed to `localFont()` in the generated file (relative to the definition file’s directory).
   * Default `../../public/fonts` or `ATOMIC_FONTS_SRC_PREFIX`. If you change `fontsOutputDir`, set this accordingly.
   */
  localFontSrcPrefix?: string
}

function resolveOptions(overrides?: RunDownloadFontsOptions) {
  return {
    fontsOutputDir: overrides?.fontsOutputDir ?? process.env.ATOMIC_FONTS_OUTPUT_DIR ?? './public/fonts',
    definitionFile: overrides?.definitionFile ?? process.env.ATOMIC_FONTS_DEFINITION_FILE ?? './src/app/definition.ts',
    envFile: overrides?.envFile ?? process.env.ATOMIC_FONTS_ENV_FILE ?? './.env',
    localFontSrcPrefix: overrides?.localFontSrcPrefix ?? process.env.ATOMIC_FONTS_SRC_PREFIX ?? '../../public/fonts',
  }
}

export async function runDownloadFonts(overrides?: RunDownloadFontsOptions): Promise<void> {
  const opts = resolveOptions(overrides)
  dotenv.config({ path: opts.envFile })

  let hasWarnings = false

  function warn(message: string, error?: unknown) {
    hasWarnings = true
    console.warn(message)
    if (error) console.warn(error)
  }

  const requiredEnvVars = {
    LIVE_SITE_URL: process.env.LIVE_SITE_URL,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    SCRIPT_USER_EMAIL: process.env.SCRIPT_USER_EMAIL,
    SCRIPT_USER_PASSWORD: process.env.SCRIPT_USER_PASSWORD,
  }

  for (const [key, value] of Object.entries(requiredEnvVars)) {
    if (!value) warn(colors.red(`Missing required environment variable: ${key}`))
  }

  const sdk = new PayloadSDK<any>({ baseURL: `${process.env.LIVE_SITE_URL}/api` })

  const FONT_FILES_DIR = opts.fontsOutputDir
  const FONT_DEFINITION_FILE = opts.definitionFile
  const localPrefix = opts.localFontSrcPrefix.replace(/\/$/, '')

  function generateFontDefinitions(extensions: FontExtensions): void {
    const configs: Array<{ name: string; type: GenericFontFamily; extension: string; variable: string }> = [
      { name: 'fontSans', type: 'sans', extension: extensions.sans, variable: '--font-setSans' },
      { name: 'fontSerif', type: 'serif', extension: extensions.serif, variable: '--font-setSerif' },
      { name: 'fontMono', type: 'mono', extension: extensions.mono, variable: '--font-setMono' },
      { name: 'fontDisplay', type: 'display', extension: extensions.display, variable: '--font-setDisplay' },
    ]

    const available = configs.filter((c) => c.extension)
    const declarations = available
      .map((c) => `const ${c.name} = localFont({ src: '${localPrefix}/${c.type}.${c.extension}', variable: '${c.variable}' })`)
      .join('\n')
    const exports = available.map((c) => c.name).join(', ')

    fs.mkdirSync(path.dirname(FONT_DEFINITION_FILE), { recursive: true })

    fs.writeFileSync(
      FONT_DEFINITION_FILE,
      `// DO NOT EDIT MANUALLY. THIS FILE IS AUTOMATICALLY GENERATED.
${declarations.length === 0 ? '//eslint-disable-next-line' : ''}
import localFont from 'next/font/local'

${declarations || '// No fonts available'}

const fonts = { ${exports} }
export default fonts
`,
    )
  }

  function ensureFontOutputs() {
    if (!fs.existsSync(FONT_FILES_DIR)) fs.mkdirSync(FONT_FILES_DIR, { recursive: true })

    for (const file of fs.readdirSync(FONT_FILES_DIR)) fs.unlinkSync(path.join(FONT_FILES_DIR, file))

    generateFontDefinitions({ sans: '', serif: '', mono: '', display: '' })
  }

  async function downloadFile(fileUrl: string, outputPath: string): Promise<void> {
    const file = fs.createWriteStream(outputPath)
    return new Promise((resolve, reject) => {
      https
        .get(fileUrl, (res) => {
          res.pipe(file)
          file.on('finish', () => {
            file.close((err) => {
              if (err) reject(err)
              else resolve()
            })
          })
        })
        .on('error', (err) => {
          if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath)
          reject(err)
        })
    })
  }

  async function downloadFont(font: Font | string | null, fontType: GenericFontFamily, baseUrl: string): Promise<string | undefined> {
    if (typeof font === 'string') {
      warn(colors.orange(`The ${fontType} font is a string reference`))
      return
    }
    if (!font?.filename) {
      warn(colors.orange(`No ${fontType} font found`))
      return
    }

    try {
      const extension = font.filename.split('.').pop()?.toLowerCase() || 'ttf'
      await downloadFile(`${baseUrl}/${font.filename}?download=1`, path.join(FONT_FILES_DIR, `${fontType}.${extension}`))
      console.log(`${colors.green('✓')} Downloaded ${fontType} font`)
      return extension
    } catch (err) {
      warn(colors.red(`Failed to download ${fontType} font`), err)
    }
  }

  console.log(colors.blue('Starting Font Download...\n'))

  ensureFontOutputs()

  if (hasWarnings) {
    console.warn(colors.orange('Font download failed — No fonts will be used'))
    return
  }

  const blobToken = process.env.BLOB_READ_WRITE_TOKEN as string
  const accountId = blobToken.split('_').slice(-2, -1)[0]
  const baseUrl = `https://${accountId}.public.blob.vercel-storage.com`

  let user: Awaited<ReturnType<typeof sdk.login>> | undefined
  try {
    user = await sdk.login({
      collection: 'users',
      data: {
        email: process.env.SCRIPT_USER_EMAIL as string,
        password: process.env.SCRIPT_USER_PASSWORD as string,
      },
    })
  } catch (err) {
    warn(colors.red('Authentication failed'), err)
    return
  }

  const token = (user as { token: string }).token

  let designSet: Awaited<ReturnType<typeof sdk.find>> | undefined
  try {
    designSet = await sdk.find(
      { collection: 'designSet', where: { active: { equals: true } }, limit: 1 },
      { headers: { Authorization: `JWT ${token}` } },
    )
  } catch (err) {
    warn(colors.red('Failed to fetch design set'), err)
    return
  }

  if (!designSet.docs.length) return warn(colors.red('No active design set found'))

  const fonts = (designSet.docs[0] as { font?: Record<string, Font | string | null | undefined> }).font
  if (!fonts) return warn(colors.red('No font configuration found'))

  const hasProcessableFonts = Object.values(fonts).some((font) => typeof font === 'object' && font !== null && 'filename' in font)
  if (!hasProcessableFonts) return console.log(colors.green('No valid fonts to process. Continuing build process.'))

  console.log(colors.green('✓ Font configuration found\n'))

  const extensions: FontExtensions = { sans: '', serif: '', mono: '', display: '' }
  const entries = Object.entries(fonts) as Array<[GenericFontFamily, Font | string | null]>

  const results = await Promise.all(entries.map(([key, font]) => downloadFont(font, key, baseUrl)))

  entries.forEach(([key], i) => {
    extensions[key] = results[i] ?? ''
  })

  if (hasWarnings) {
    console.warn(colors.orange('\n⚠ Warnings encountered — No fonts will be used.'))
    return
  }

  generateFontDefinitions(extensions)
  console.log(colors.green('\n✓ Font definitions generated successfully\n'))
}
