#!/usr/bin/env node
/**
 * Post-generation step that writes a sibling `payload-types.augment.d.ts`
 * next to the generated `payload-types.ts`. The augment file wires the
 * project's concrete types into `@pro-laico/ap-types`'s `PayloadAugment`
 * interface so package consumers (ap-actions, ap-child-blocks, ap-site, …)
 * resolve to project-specific shapes instead of the permissive `Get<>`
 * fallbacks.
 *
 * Why a separate file: inside a `declare module 'X' { … }` block, identifiers
 * resolve in module X's scope, not the surrounding file's. So we need an
 * outer-scope `import type { Page } from './payload-types'` to reference the
 * concrete types — which means a file separate from payload-types.ts itself.
 *
 * Stub names are discovered from `packages/ap-types/src/payload-types.ts` —
 * any name defined there as `Get<'Name', …>` is a candidate. Only names that
 * the project actually exports get mapped, so adding/removing collections in
 * Payload doesn't break the augment.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const templateRoot = path.resolve(__dirname, '..')
const generatedPath = path.join(templateRoot, 'payload-types.ts')
const augmentPath = path.join(templateRoot, 'payload-types.augment.d.ts')
const apTypesStubsPath = path.resolve(templateRoot, '..', '..', 'packages', 'ap-types', 'src', 'payload-types.ts')

const apTypesStubs = fs.readFileSync(apTypesStubsPath, 'utf8')
const stubNames = Array.from(apTypesStubs.matchAll(/^export type ([A-Za-z][A-Za-z0-9_]*) = Get</gm)).map((m) => m[1])

const generatedContent = fs.readFileSync(generatedPath, 'utf8')
const exportedNames = new Set(
  Array.from(generatedContent.matchAll(/^export (?:type|interface) ([A-Za-z][A-Za-z0-9_]*)\b/gm)).map((m) => m[1]),
)

// Strip any prior augmentation block that may have been written into
// payload-types.ts during the earlier single-file experiment.
const SENTINEL_START = '// ===== BEGIN @pro-laico/ap-types augmentation (auto-generated) ====='
const SENTINEL_END = '// ===== END @pro-laico/ap-types augmentation ====='
if (generatedContent.includes(SENTINEL_START)) {
  const cleaned = generatedContent.replace(new RegExp(`\\n${SENTINEL_START}[\\s\\S]*?${SENTINEL_END}\\n?`, 'g'), '')
  fs.writeFileSync(generatedPath, cleaned.trimEnd() + '\n')
}

const mappable = stubNames.filter((name) => exportedNames.has(name))
const mappings = mappable.map((name) => `    ${name}: G.${name}`).join('\n')

const file = `// AUTO-GENERATED by scripts/appendPayloadAugment.mjs — do not edit by hand.
// Regenerated whenever \`pnpm generate:types\` runs.

import type * as G from './payload-types'

declare module '@pro-laico/ap-types/schema' {
  interface PayloadAugment {
${mappings}
  }
}

declare module '@pro-laico/ap-types' {
  interface PayloadAugment {
${mappings}
  }
}
`

fs.writeFileSync(augmentPath, file)
console.log(`[augment] wrote ${path.relative(process.cwd(), augmentPath)} (${mappable.length} types)`)
