// DO NOT EDIT MANUALLY. THIS FILE IS AUTOMATICALLY GENERATED.

import localFont from 'next/font/local'

const fontSans = localFont({ src: '../../public/fonts/sans.woff2', variable: '--font-setSans' })
const fontSerif = localFont({ src: '../../public/fonts/serif.woff2', variable: '--font-setSerif' })
const fontMono = localFont({ src: '../../public/fonts/mono.woff2', variable: '--font-setMono' })
const fontDisplay = localFont({ src: '../../public/fonts/display.woff2', variable: '--font-setDisplay' })

const fonts = { fontSans, fontSerif, fontMono, fontDisplay }
export default fonts
