// AUTO-GENERATED by @pro-laico/core/scripts/appendPayloadAugment.mjs — do not edit by hand.
// Regenerated whenever `pnpm generate:types` runs.

import type * as G from './payload-types'

declare module '@pro-laico/core' {
  interface PayloadAugment {
    Font: G.Font
    FontOptimized: G.FontOptimized
    FontOriginal: G.FontOriginal
    FontSet: G.FontSet
  }
}
